db.driver.name=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://REDACTED_HOST:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
db.username=root
db.password=REDACTED_PASSWORD
hello=java